// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAElgHDVVek5fbUMxeJ9lda8ZOYJitxKOs',
    appId: '1:672885252034:web:aa61d579b352bff868405b',
    messagingSenderId: '672885252034',
    projectId: 'fcm-app-34f9a',
    authDomain: 'fcm-app-34f9a.firebaseapp.com',
    storageBucket: 'fcm-app-34f9a.appspot.com',
    measurementId: 'G-MPP3E2BGL5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBmM7lirlh6lmUD1tD25ipjnNVEtmjyF7w',
    appId: '1:672885252034:android:60674d04d61c593b68405b',
    messagingSenderId: '672885252034',
    projectId: 'fcm-app-34f9a',
    storageBucket: 'fcm-app-34f9a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDefast3QIgfEh2idY9IBZdzCP_d8ClGuo',
    appId: '1:672885252034:ios:acb481f62f8cbc3c68405b',
    messagingSenderId: '672885252034',
    projectId: 'fcm-app-34f9a',
    storageBucket: 'fcm-app-34f9a.appspot.com',
    iosBundleId: 'com.safiribytes.fcm',
  );
}
